updated config file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,136 +1,79 @@
-name: Build test and deploy to package repository
+name: Python Package Publishing Pipeline
+
+on:
+  push:
+    branches:
+      - main # Run on push to main branch
+  pull_request:
+    branches:
+      - main # Run on pull request to main branch
+
 env:
   TZ: 'America/New_York'
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
   TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
-on:
-  push:
-    branches:
-      - main
-      - release
-      - feature/*
-      - hotfix/*
-      - dalexander/*
-  pull_request:
-    branches:
-      - main
-  release:
-    types: [ published ]
-    branches:
-      - main
 
 jobs:
-  setup-and-test:
+  setup_and_test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: [ "3.8", "3.9",  "3.10" ]
+        python-version: [3.8, 3.9, 3.10]
+
     steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
       - name: Install Python
         uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
           architecture: x64
-      - name: Checkout
-        uses: actions/checkout@v2
 
-      - name: Setup Docker Compose services
-        env:
-          POSTGRES_DB: testdb
-          POSTGRES_USER: alpha
-          POSTGRES_PASSWORD: alphapassword
-          POSTGRES_VERSION: 13
-          POSTGRES_HOST: 127.0.0.1
-          POSTGRES_PORT: 5432
-          MYSQL_DATABASE: testdb
-          MYSQL_USER: alpha
-          MYSQL_PASSWORD: alphapassword
-          MYSQL_ROOT_PASSWORD: alphapassword
-          MYSQL_HOST: 127.0.0.1
-          MYSQL_PORT: 3306
-          MARIADB_DATABASE: testdb
-          MARIADB_USER: alpha
-          MARIADB_PASSWORD: alphapassword
-          MARIADB_ROOT_PASSWORD: alphapassword
-          MARIADB_HOST: 127.0.0.1
-          MARIADB_PORT: 3307
+      - name: Setup Environment Variables for Database Services
         run: |
-          printf """
-          LOG_LEVEL="DEBUG"
-          MARIADB_DATABASE=$MARIADB_DATABASE
-          MARIADB_USER=$MARIADB_USER
-          MARIADB_PASSWORD=$MARIADB_PASSWORD
-          MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
-          MARIADB_ROOT_PASSWORD_HASH=""
-          MARIADB_HOST=$MARIADB_HOST
-          MARIADB_PORT=$MARIADB_PORT
-          # ##########################################################
-          MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
-          MYSQL_DATABASE=$MYSQL_DATABASE
-          MYSQL_USER=$MYSQL_USER
-          MYSQL_PASSWORD=$MYSQL_PASSWORD
-          MYSQL_ALLOW_EMPTY_PASSWORD=no
-          MYSQL_RANDOM_ROOT_PASSWORD=no
-          MYSQL_ONETIME_PASSWORD=no
-          MYSQL_INITDB_SKIP_TZINFO=no
-          MYSQL_HOST=$MYSQL_HOST
-          MYSQL_PORT=$MYSQL_PORT
-          # ##########################################################
-          POSTGRES_DB=$POSTGRES_DB
-          POSTGRES_USER=$POSTGRES_USER
-          POSTGRES_PASSWORD=$POSTGRES_PASSWORD
-          POSTGRES_INITDB_ARGS=
-          POSTGRES_INITDB_WALDIR=
-          POSTGRES_HOST_AUTH_METHOD=scram-sha-256
-          PGDATA=/var/lib/postgresql/data
-          POSTGRES_PORT=$POSTGRES_PORT
-          POSTGRES_VERSION=$POSTGRES_VERSION
-          POSTGRES_HOST=$POSTGRES_HOST
-          # ##########################################################
-          """ > .env
-          docker-compose -p crudrepository up \
-          --always-recreate-deps \
-          --renew-anon-volumes \
-          --remove-orphans \
-          --force-recreate \
-          -d --build && wait $!
+          echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
+          # Define other required environment variables for database services here...
+
+      - name: Setup Docker Compose Services
+        run: docker-compose -f docker-compose.yml up -d --build
+
+      - name: Install Dependencies and Run Tests
+        run: |
           /bin/bash deploy.sh -uv --install-dev && wait $!
-          docker ps -a
+          /bin/bash deploy.sh --test && wait $!
 
-      # Task for linting with black
-      - name: Lint with black
+      - name: Lint with Black
+        run: black crud_repository && black --check crud_repository
+
+      - name: Check Test Results
         run: |
-          # Code formatting with black, check every python file in the crud_repository directory 
-          black crud_repository
-          black --check crud_repository
+          TEST_RESULTS=$(echo "::set-output name=test_results::$(find . -name 'test_results.xml')"
+          echo "$TEST_RESULTS")
+          if [[ -z "$TEST_RESULTS" ]]; then
+            echo "Error: Test results not found. Exiting..."
+            exit 1
+          fi
 
-      # Task for running tests
-      - name: Testing with pytest
-        run: |
-          /bin/bash deploy.sh --test  && wait $!
-          echo "Test results: $?"
 
-  build:
-    needs: setup-and-test
+  build_and_publish:
+    needs: setup_and_test
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.8", "3.9",  "3.10" ]
+        python-version: [3.8, 3.9, 3.10]
+
+    if: ${{ steps.setup_and_test.outputs.test_results == 'success' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}
+
     steps:
-      - name: Checkout
+      - name: Checkout Code
         uses: actions/checkout@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-          architecture: x64
 
-      - name: Build package artifact
-        run: |
-          /bin/bash deploy.sh --install-dev --build && wait $!
+      - name: Build Package Artifact
+        run: /bin/bash deploy.sh --install-dev --build && wait $!
 
-      - name: Upload build artifact
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Upload Build Artifact
         uses: actions/upload-artifact@v2
         with:
           name: Build-Results
@@ -140,16 +83,7 @@ jobs:
             README.md
             LICENSE
 
-  publish:
-    needs: build
-    runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
-    # only run if job setup and test passed
-    strategy:
-      matrix:
-        python-version: ["3.8", "3.9",  "3.10" ]
-    steps:
-      - name: Download build artifact
+      - name: Download Build Artifact
         uses: actions/download-artifact@v2
         with:
           name: Build-Results
@@ -161,4 +95,5 @@ jobs:
           TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
           TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
         run: |
-          /bin/bash deploy.sh --install-dev --publish && wait $!
+          python -m build --wheel
+          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
