updated config file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -111,7 +111,12 @@ jobs:
       # Task for running tests
       - name: Testing with pytest
         run: |
-          /bin/bash deploy.sh --test  && wait $!
+          if python3 -m pytest tests/ 2>&1 ; then
+              echo "Tests completed Successfully."
+          else
+              echo "Tests failed to complete successfully."
+              exit 1
+          fi
 
   build:
     needs: setup-and-test
